[package]
name = 'components'
version = '0.1.0'
edition = '2021'

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = 'components'
path = 'src/components.rs'

[[bin]]
name = 'jet'
path = 'src/jet.rs'

[lib]

[dependencies]
stl_io = '*'
